config/routes.rb
AwEphIt::Application.routes.draw do

  get '/index' => "game_search#index"
  get '/list' => "game_search#list"
  get '/game_search' => "game_search#index"
  
  resources :rules
  resources :sources
  resources :gameingredients
  resources :ingredients do
    get 'random_rule'
  end
  resources :gamelocations
  resources :locations
  resources :games

  root :to => 'game_search#index'
  
  get "crawler/" => "games#crawler2"

end

app/models/gameingredient.rb
class Gameingredient < ActiveRecord::Base
  
  belongs_to :game
  belongs_to :ingredient
  
end

app/controllers/gameingredients_controller.rb
class GameingredientsController < ApplicationController
  # GET /gameingredients
  # GET /gameingredients.xml
  def index
    @gameingredients = Gameingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @gameingredients }
    end
  end

  # GET /gameingredients/1
  # GET /gameingredients/1.xml
  def show
    @gameingredient = Gameingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @gameingredient }
    end
  end

  # GET /gameingredients/new
  # GET /gameingredients/new.xml
  def new
    @gameingredient = Gameingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @gameingredient }
    end
  end

  # GET /gameingredients/1/edit
  def edit
    @gameingredient = Gameingredient.find(params[:id])
  end

  # POST /gameingredients
  # POST /gameingredients.xml
  def create
    @gameingredient = Gameingredient.new(params[:gameingredient])

    respond_to do |format|
      if @gameingredient.save
        format.html { redirect_to(@gameingredient, :notice => 'Gameingredient was successfully created.') }
        format.xml  { render :xml => @gameingredient, :status => :created, :location => @gameingredient }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @gameingredient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /gameingredients/1
  # PUT /gameingredients/1.xml
  def update
    @gameingredient = Gameingredient.find(params[:id])

    respond_to do |format|
      if @gameingredient.update_attributes(params[:gameingredient])
        format.html { redirect_to(@gameingredient, :notice => 'Gameingredient was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @gameingredient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /gameingredients/1
  # DELETE /gameingredients/1.xml
  def destroy
    @gameingredient = Gameingredient.find(params[:id])
    @gameingredient.destroy

    respond_to do |format|
      format.html { redirect_to(gameingredients_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/gameingredients_helper.rb
module GameingredientsHelper
end

app/views/gameingredients/_form.html.erb
<%= form_for(@gameingredient) do |f| %>
  <% if @gameingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gameingredient.errors.count, "error") %> prohibited this gameingredient from being saved:</h2>

      <ul>
      <% @gameingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.text_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :ingredient_id %><br />
    <%= f.text_field :ingredient_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gameingredients/edit.html.erb
<h1>Editing gameingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @gameingredient %> |
<%= link_to 'Back', gameingredients_path %>

app/views/gameingredients/index.html.erb
<h1>Listing gameingredients</h1>

<table>
  <tr>
    <th>Game</th>
    <th>Ingredient</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gameingredients.each do |gameingredient| %>
  <tr>
    <td><%= gameingredient.game_id %></td>
    <td><%= gameingredient.ingredient_id %></td>
    <td><%= link_to 'Show', gameingredient %></td>
    <td><%= link_to 'Edit', edit_gameingredient_path(gameingredient) %></td>
    <td><%= link_to 'Destroy', gameingredient, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gameingredient', new_gameingredient_path %>

app/views/gameingredients/new.html.erb
<h1>New gameingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', gameingredients_path %>

app/views/gameingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @gameingredient.game_id %>
</p>

<p>
  <b>Ingredient:</b>
  <%= @gameingredient.ingredient_id %>
</p>


<%= link_to 'Edit', edit_gameingredient_path(@gameingredient) %> |
<%= link_to 'Back', gameingredients_path %>