config/routes.rb
AwEphIt::Application.routes.draw do

  get '/index' => "game_search#index"
  get '/list' => "game_search#list"
  get '/game_search' => "game_search#index"
  
  resources :rules
  resources :sources
  resources :gameingredients
  resources :ingredients do
    get 'random_rule'
  end
  resources :gamelocations
  resources :locations
  resources :games

  root :to => 'game_search#index'
  
  get "crawler/" => "games#crawler2"

end

app/models/gamelocation.rb
class Gamelocation < ActiveRecord::Base
  
  belongs_to :game
  belongs_to :location
end

app/controllers/gamelocations_controller.rb
class GamelocationsController < ApplicationController
  # GET /gamelocations
  # GET /gamelocations.xml
  def index
    @gamelocations = Gamelocation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @gamelocations }
    end
  end

  # GET /gamelocations/1
  # GET /gamelocations/1.xml
  def show
    @gamelocation = Gamelocation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @gamelocation }
    end
  end

  # GET /gamelocations/new
  # GET /gamelocations/new.xml
  def new
    @gamelocation = Gamelocation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @gamelocation }
    end
  end

  # GET /gamelocations/1/edit
  def edit
    @gamelocation = Gamelocation.find(params[:id])
  end

  # POST /gamelocations
  # POST /gamelocations.xml
  def create
    @gamelocation = Gamelocation.new(params[:gamelocation])

    respond_to do |format|
      if @gamelocation.save
        format.html { redirect_to(@gamelocation, :notice => 'Gamelocation was successfully created.') }
        format.xml  { render :xml => @gamelocation, :status => :created, :location => @gamelocation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @gamelocation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /gamelocations/1
  # PUT /gamelocations/1.xml
  def update
    @gamelocation = Gamelocation.find(params[:id])

    respond_to do |format|
      if @gamelocation.update_attributes(params[:gamelocation])
        format.html { redirect_to(@gamelocation, :notice => 'Gamelocation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @gamelocation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /gamelocations/1
  # DELETE /gamelocations/1.xml
  def destroy
    @gamelocation = Gamelocation.find(params[:id])
    @gamelocation.destroy

    respond_to do |format|
      format.html { redirect_to(gamelocations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/gamelocations_helper.rb
module GamelocationsHelper
end

app/views/gamelocations/_form.html.erb
<%= form_for(@gamelocation) do |f| %>
  <% if @gamelocation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gamelocation.errors.count, "error") %> prohibited this gamelocation from being saved:</h2>

      <ul>
      <% @gamelocation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.text_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.text_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gamelocations/edit.html.erb
<h1>Editing gamelocation</h1>

<%= render 'form' %>

<%= link_to 'Show', @gamelocation %> |
<%= link_to 'Back', gamelocations_path %>

app/views/gamelocations/index.html.erb
<h1>Listing gamelocations</h1>

<table>
  <tr>
    <th>Game</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gamelocations.each do |gamelocation| %>
  <tr>
    <td><%= gamelocation.game_id %></td>
    <td><%= gamelocation.location_id %></td>
    <td><%= link_to 'Show', gamelocation %></td>
    <td><%= link_to 'Edit', edit_gamelocation_path(gamelocation) %></td>
    <td><%= link_to 'Destroy', gamelocation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gamelocation', new_gamelocation_path %>

app/views/gamelocations/new.html.erb
<h1>New gamelocation</h1>

<%= render 'form' %>

<%= link_to 'Back', gamelocations_path %>

app/views/gamelocations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @gamelocation.game_id %>
</p>

<p>
  <b>Location:</b>
  <%= @gamelocation.location_id %>
</p>


<%= link_to 'Edit', edit_gamelocation_path(@gamelocation) %> |
<%= link_to 'Back', gamelocations_path %>