config/routes.rb
AwEphIt::Application.routes.draw do

  get '/index' => "game_search#index"
  get '/list' => "game_search#list"
  get '/game_search' => "game_search#index"
  
  resources :rules
  resources :sources
  resources :gameingredients
  resources :ingredients do
    get 'random_rule'
  end
  resources :gamelocations
  resources :locations
  resources :games

  root :to => 'game_search#index'
  
  get "crawler/" => "games#crawler2"

end

app/views/layouts/_dev_footer.html.erb
<footer>
<hr>
Dev Links<br />
<%= link_to "Home", index_path %><br />
<%= link_to "Games", games_path %> <%= link_to "Locations", locations_path %> <%= link_to "Ingredients", ingredients_path %> <%= link_to "Sources", sources_path %> <%= link_to "Rules", rules_path %><br />
<%= link_to "GameLocations", gamelocations_path %> <%= link_to "GameIngredients", gameingredients_path %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript" src="http://use.typekit.com/sox7njt.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
	  <%= javascript_include_tag :defaults %>
  	<%= stylesheet_link_tag "jquery-ui-1.8.17.custom.css" %>
	<%= javascript_include_tag "jquery-1.7.1.min.js" %>
	<%= javascript_include_tag "jquery-ui-1.8.17.custom.min.js" %>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
	<style type="text/css">
	.hidden-loc {
    	display: none;
	}
	.hidden-complex {
		display: none;
	}
	.filters {
		padding: 10px !important;
	}
	#slider-complex {
		margin-top: 10px;
		margin-bottom: 5px;
		width: 95px;
	}
	#slide { float: right; margin-right: 10px; font-size: 11px; text-shadow: 1px 1px 1px #888; color: #FFF; width:106px; }
	
	#filters { float: right; width: 104px; margin-left: 10px; margin-right: 10px; }
		#filters ul { list-style: none; padding:0; margin:0; }
		#filters li { float: right;  font-size: 11px; text-shadow: 1px 1px 1px #888; margin-right: 2px; color: #FFF; width: 50px; padding: 5px 0; }
		#filters label { display: block; padding: 0px; text-align: center; }
		#filters input { margin-bottom: 6px;}
	
	</style>
	<script language="javascript">
		$(function(){
			$('#slider-complex').slider({
				value:5,
				min: 1,
				max: 5,
				orientation: 'horizontal',
			});
			$( "#slider-complex" ).bind( "slide", function(event, ui) {
			  filter_complexity(0,ui.value);
			});
		});
		function hide_domestic() {
			if ($("#domestic").attr('checked')) {
				$(".domestic").removeClass("hidden-loc");
			} else {
				$(".domestic").addClass("hidden-loc");
			}
		}
		function hide_import() {
			if ($("#import").attr('checked')) {
				$(".import").removeClass("hidden-loc",1000);
			} else {
				$(".import").addClass("hidden-loc",1000);
			}
		}
		function filter_complexity(mincomplexity, maxcomplexity) {
			$(".complex1").removeClass("hidden-complex");
			$(".complex2").removeClass("hidden-complex");
			$(".complex3").removeClass("hidden-complex");
			$(".complex4").removeClass("hidden-complex");
			$(".complex5").removeClass("hidden-complex");
			if (mincomplexity > 1) {
				$(".complex1").addClass("hidden-complex");
			}
			if (mincomplexity > 2 || maxcomplexity < 2) {
				$(".complex2").addClass("hidden-complex");
			}
			if (mincomplexity > 3 || maxcomplexity < 3) {
				$(".complex3").addClass("hidden-complex");
			}
			if (mincomplexity > 4 || maxcomplexity < 4) {
				$(".complex4").addClass("hidden-complex");
			}
			if (maxcomplexity < 5) {
				$(".complex5").addClass("hidden-complex");
			}
		}
	</script>
  <title>Aw Chug It</title>
  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-8644159-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>

<DIV id="wrapper">

<%= yield %>

</DIV>
</body>
</html>